
site:
  theme: 'Editorial'
  baseUrl: 'http://andikapratama.github.io/OrchidTutorials'
  about:
    siteName: Kotlin Project
    siteDescription: This is a short description of this project.

theme:
  primaryColor: '#DE9149'
  legacySearch: false
  social:
    github: 'andikapratama/OrchidTutorials'
  metaComponents:
    - type: 'orchidSearch'
  menu:
    - type: 'separator'
      title: 'Wiki'
    - type: 'wiki'
    - type: 'page'
      itemId: 'Changelog'
    - type: 'separator'
      title: 'API Docs'
    - type: 'sourcedocPages'
      moduleType: 'kotlindoc'
      node: 'classes'
      asSubmenu: true
      submenuTitle: 'Classes'
    - type: 'sourcedocPages'
      moduleType: 'kotlindoc'
      node: 'packages'
      asSubmenu: true
      submenuTitle: 'Packages'

kotlindoc:
  sourceDirs:
    - './../../../../app/src/main/kotlin'
  pages:
    menu:
      - type: 'sourcedocPageLinks'
        moduleType: 'kotlindoc'
        itemTitleType: 'SIGNATURE'
        includeItems: true

services:
  publications:
    stages:
      githubPages:
        branch: gh-pages
        repo: 'OrchidTutorials'
        username: 'andikapratama'
      githubReleases:
        repo: 'andikapratama/OrchidTutorials'
